config/routes.rb
Rails.application.routes.draw do
  get 'lobby/index'
  resources :rooms
  root 'lobby#index'
  resources :rooms do
  	resources :questions do
		resources :answers
	end
  end
  scope '/rooms' do
  	post '/auth' => 'rooms#auth'
    get '/quiz/:id' => 'rooms#quiz'
    get '/quiz/:id/finished' => 'rooms#finished'
    get '/present/:id' => 'rooms#present'
    get '/kick/:id/:username' => 'rooms#kick'

    get '/quiz/:id/question/:question_id' => 'rooms#get_quiz_question'
    post '/quiz/:id/question/:question_id' => 'rooms#post_quiz_question'
    get '/remote/:id/next' => 'rooms#next_question'
    get '/remote/:id' => 'rooms#remote'
    get '/reset/:id' => 'rooms#reset'
  end

  get '/api/active/:id' => 'json_api#active'
  get '/api/responses/:question_id' => 'json_api#responses'
  get '/api/student_info/:room_id' => 'json_api#infos'

  #scope '/join_room' do
   # post 'show' => 'join_room#show'
    #get 'show' => 'join_room#show'
    #path 'join_room_path' =>
  #end
  resources :join_room
  scope '/join_room' do
   post 'show' => 'join_room#create'
    get 'show' => 'join_room#show'
    end

  get '/:roomcode' => 'rooms#roomglob', constraints: { site_name: /[A-Z]{4}/ }
end

app/models/room.rb
class Room < ApplicationRecord
	has_many :questions, dependent: :destroy
	has_many :student_infos, dependent: :destroy
	validates :name, presence: true
	validates :password, presence: true,
						length: { minimum: 2 }
	validates :roomcode, presence: true,
						length: {is: 4} , format: { with: /\A[a-zA-Z]+\z/}
	validates_uniqueness_of :roomcode
end

app/controllers/rooms_controller.rb
require 'simple-password-gen'

class RoomsController < ApplicationController

  def new
    @room = Room.new
  end

  def get_quiz_question
    @room = Room.find(params[:id])
    @question_idx = params[:question_id].to_i;
    @question = @room.questions[params[:question_id].to_i - 1]
    @username = session[:username]

    if @question.nil?
      redirect_to '/rooms/quiz/' + @room.id.to_s + '/finished'
    else
      render 'quiz_question'
    end
  end

  def present
    @room = Room.find(params[:id])

    if not @room.active_question.nil?
      @question_idx = @room.active_question
      @question = @room.questions[@question_idx - 1]
    end

    render 'present2', :layout => false
  end

  def roomglob
	redirect_to '/join_room/show?code=' + params[:roomcode]
  end

  def kick
    @room = Room.find(params[:id])
    @user = params[:username]

    StudentInfo.find_by(room_id: @room.id, name: @user).destroy

    redirect_to '/rooms/remote/' + @room.id.to_s
  end


  def finished
    @room = Room.find(params[:id])
    render 'finished'
  end

  def remote
    @room = Room.find(params[:id])
    @room.state = "active"

    if @room.save

      render 'remote'
    end
  end

  def post_quiz_question
    @room = Room.find(params[:id])

    unless session.has_key? :username
      redirect_to '/rooms/quiz/' + @room.id.to_s
      return
    end

    @question = @room.questions[params[:question_id].to_i - 1]

    @res = Response.create(question_id: @question.id,
                           answer_id: @question.answers[params[:response].to_i].id,
                           answeridx: params[:response].to_i,
                           username: session[:username],
                           student_info_id: session[:info_id])

    redirect_to '/rooms/quiz/' + @room.id.to_s
  end

  def next_question
    @room = Room.find(params[:id])

    if @room.active_question.nil?
      @room.active_question = 1
    else
      @room.active_question += 1

      if @room.active_question >= @room.questions.length
        redirect_to '/rooms/quiz/' + @room.id.to_s + '/finished'
        @room.state = "finished"
        @room.save
        return
      end
    end

    @room.save

    redirect_to '/rooms/remote/' + @room.id.to_s
  end

  def reset
    @room = Room.find(params[:id])
    @room.active_question = nil
    @room.state = nil
    @room.save
    @room.student_infos.destroy_all


    redirect_to @room
  end

  def quiz
    @room = Room.find(params[:id])
    @username = session[:username]

    # find most recent response
    @last_res = Response.order("created_at DESC").find_by_username(@username)
    @has_res = @last_res.present?

    # ### it turns out here that @has_res is false.
    if @has_res
      @finished = @last_res.question_id == @room.questions.last.id
    end

    if @has_res
      @last_res_text = Answer.find(@last_res.answer_id).text
    end

    render 'quiz'
  end

  def show

    @room = Room.find(params[:id])

    if authed?
      render 'show'
    else
      render 'unauthed'
    end
  end

  def destroy
    @room = Room.find(params[:id])
    session[:rooms].delete(@room.id)
    #print(@room.id)
    @room.destroy

    redirect_to '/'
  end

  def authed?
    unless session.has_key? :rooms
      return false
    end

    return session[:rooms].include? params[:id].to_i
  end

  def auth
    @room = Room.find(params[:id])
    if params[:password] == @room.password
      if not session.has_key?(:rooms)
        session[:rooms] = []
      end
      session[:rooms].push(@room.id.to_i)
      redirect_to @room
    else
      flash[:auth] = "Wrong password"
      render 'unauthed'
    end
  end

  def create
    pwd = Password.pronounceable 8
    code = generate_roomcode

    @room = Room.new(room_params.merge(:password => pwd, :roomcode => code))

    if @room.save
      if not session.has_key?(:rooms)
        session[:rooms] = []
      end

      session[:rooms].push(@room.id)
      redirect_to @room
    else
      render 'new'
    end
  end

  private
  def room_params
    params.require(:room).permit(:name)
  end

  def generate_roomcode
    @code = [*('A'..'Z')].sample(4).join
    while (Room.find_by_roomcode (@code).present?)
      @code = [*('A'..'Z')].sample(4).join
    end

    return @code

  end

end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/_kick.html.erb
<script>
  var username = "<%= @username %>";


  setInterval(function() {
      $.get('/api/student_info/' + room_id, function(data) {
          var names = data.map(function(x) {
              return x.name;
          });
          if(names.indexOf(username) < 0) {
              // kick
              window.location.href = '/';
          }
      });
  }, 200);
</script>

app/views/rooms/_kickusers.html.erb
<script>
    var room_id = "<%= @room.id %>";


    setInterval(function() {
        $.get('/api/student_info/' + room_id, function(data) {
            var names = data.map(function(x) {
                return x.name;
            });

            var lis = Array.from(document.getElementsByClassName("kickable"));
            var li_names = lis.map(function(x) { return x.id.split('_')[1]; });

            for(var name of li_names) {
                if(names.indexOf(name) < 0) {
                    document.getElementById('li_' + name).outerHTML = "";
                }
            }

            var users = document.getElementById("users");

            for(var name of names) {
                if(li_names.indexOf(name) < 0) {
                    users.innerHTML += '<li class="kickable" id="li_' + name + '">' +
                        '' + name + '<a class="button" id="kick_' + name + '" href="/rooms/kick/<%= @room.id %>/'+name+'">Kick</a>' +
                        '</li>';
                }
            }
        });
    }, 200);
</script>

<style>

  #users {
    list-style-type: none;
    width: 300px;
  }
  .kickable {
    float: left;
    display: inline;
    width: 300px;
  }
  .kickable > a {
    float: right;
  }
</style>

<ul id="users" style="background: rgba(0, 0, 0, 0);">
  <% @room.student_infos.each do |info| %>
      <li class="kickable" id="li_<%= info.name %>">
        <%= info.name %> <a class="button" id="kick_<%= info.name %>" href="/rooms/kick/<%= @room.id %>/<%= info.name %>">Kick</a>
      </li>
  <% end %>
</ul>

app/views/rooms/_quizjs.html.erb
<script language="javascript">
    window.status = 'waiting';
    var room_id = <%= @room.id %>;
    var is_active = <%= @room.state.nil? ? 0 : 1 %>;
    var current_question = <%= @room.active_question.nil? ? -1 : @room.active_question %>;

    var job = setInterval(function() {
        $.get('/api/active/' + room_id, function(data) {

            //console.log(room_id, is_active, current_question, JSON.stringify(data));

            if(!!data.active != is_active)
        {
            window.status = 'continue';
           // console.log('reloading!');
            clearInterval(job);
            window.location.reload();
            return;
        }

        var test = false;
        if (data.question != current_question) {
            window.status = 'continue';
            //console.log('going to question', test);
            test = true;
            clearInterval(job);

            if(!presenting)
              window.location.href = '/rooms/quiz/' + room_id + '/question/' + data.question;
            else
              window.location.reload();
        }

    });
    }, 200);
</script>

app/views/rooms/_responses.html.erb
<!-- copied from d3.org -->
<style>


  svg {
    width: 100%;
    height: 100%;
  }

  path.slice{
    stroke-width:2px;
  }

  polyline{
    opacity: .3;
    stroke: black;
    stroke-width: 2px;
    fill: none;
  }

</style>
<body>

<script src="http://d3js.org/d3.v3.min.js"></script>
<script>

    var svg = d3.select("#responses")
        .append("svg")
        .append("g")

    svg.append("g")
        .attr("class", "slices");
    svg.append("g")
        .attr("class", "labels");
    svg.append("g")
        .attr("class", "lines");

    var width = document.getElementById("responses").clientWidth,
        height = 150,
        radius = Math.min(width, height) / 2;

    var pie = d3.layout.pie()
        .sort(null)
        .value(function(d) {
            return d.value;
        });

    var arc = d3.svg.arc()
        .outerRadius(radius * 0.8)
        .innerRadius(radius * 0.4);

    var outerArc = d3.svg.arc()
        .innerRadius(radius * 0.9)
        .outerRadius(radius * 0.9);


    var key = function(d){ return d.data.label; };

    var color;

    svg.attr("transform", "translate(" + width / 2 + "," + height / 2 + ")");

    var div = document.getElementById("responses");

    var alpha = 'A B C D E F G H I J K L M N O P Q R S T U V W X Y Z'.split(' ');


    setInterval(function() {

        function tostring(d) {
            return d.map(function(x) {
                return x.username + " answered: " + alpha[x.answeridx];
            });
        }

        $.get('/api/responses/' + question_id, function(data) {
            if(responses.length != data.length) {
                // find the events
                var newS = tostring(data);
                var oldS = tostring(responses);

                for(var s of newS) {
                    if(oldS.indexOf(s) < 0) {
                        event(s);
                    }
                }
                responses = data;
                change(randomData());
            }
        });
    }, 400);

    function randomData (){

        var ret = {};
        for(var r of responses) {
            if(!ret.hasOwnProperty(r.answeridx))
                ret[r.answeridx] = 1;
            else
                ret[r.answeridx]++;
        }


        color = d3.scale.ordinal()
            .domain(Object.keys(ret))
            .range(["#98abc5", "#8a89a6", "#7b6888", "#6b486b", "#a05d56", "#d0743c", "#ff8c00"]);

        var labels = color.domain();
        return labels.map(function(label){
            return { label: alpha[label] + ' (' + (ret[label] / responses.length * 100).toFixed(1) + '%)', value: ret[label] }
        });
    }

    change(randomData());

    d3.select(".randomize")
        .on("click", function(){
            change(randomData());
        });


    function change(data) {

        /* ------- PIE SLICES -------*/
        var slice = svg.select(".slices").selectAll("path.slice")
            .data(pie(data), key);

        slice.enter()
            .insert("path")
            .style("fill", function(d) { return color(d.data.label); })
            .attr("class", "slice");

        slice
            .transition().duration(1000)
            .attrTween("d", function(d) {
                this._current = this._current || d;
                var interpolate = d3.interpolate(this._current, d);
                this._current = interpolate(0);
                return function(t) {
                    return arc(interpolate(t));
                };
            })

        slice.exit()
            .remove();

        /* ------- TEXT LABELS -------*/

        var text = svg.select(".labels").selectAll("text")
            .data(pie(data), key);

        text.enter()
            .append("text")
            .attr("dy", ".35em")
            .text(function(d) {
                return d.data.label;
            });

        function midAngle(d){
            return d.startAngle + (d.endAngle - d.startAngle)/2;
        }

        text.transition().duration(1000)
            .attrTween("transform", function(d) {
                this._current = this._current || d;
                var interpolate = d3.interpolate(this._current, d);
                this._current = interpolate(0);
                return function(t) {
                    var d2 = interpolate(t);
                    var pos = outerArc.centroid(d2);
                    pos[0] = radius * (midAngle(d2) < Math.PI ? 1 : -1);
                    return "translate("+ pos +")";
                };
            })
            .styleTween("text-anchor", function(d){
                this._current = this._current || d;
                var interpolate = d3.interpolate(this._current, d);
                this._current = interpolate(0);
                return function(t) {
                    var d2 = interpolate(t);
                    return midAngle(d2) < Math.PI ? "start":"end";
                };
            });

        text.exit()
            .remove();

        /* ------- SLICE TO TEXT POLYLINES -------*/

        var polyline = svg.select(".lines").selectAll("polyline")
            .data(pie(data), key);

        polyline.enter()
            .append("polyline");

        polyline.transition().duration(1000)
            .attrTween("points", function(d){
                this._current = this._current || d;
                var interpolate = d3.interpolate(this._current, d);
                this._current = interpolate(0);
                return function(t) {
                    var d2 = interpolate(t);
                    var pos = outerArc.centroid(d2);
                    pos[0] = radius * 0.95 * (midAngle(d2) < Math.PI ? 1 : -1);
                    return [arc.centroid(d2), outerArc.centroid(d2), pos];
                };
            });

        polyline.exit()
            .remove();
    };

</script>

app/views/rooms/finished.html.erb
<span id="finished">The quiz is over. Here are the results.</span>

<div id="responses" style="width: 100%; height: 500px;">

</div>

app/views/rooms/new.html.erb
<html>
  <head>
<style type="text/css">  
  html { height: 100% }  
  body { height: 100%; margin: 0; padding: 0 }  
  #map_canvas { height: 100% }   
</style> 

<%= stylesheet_link_tag 'application' %>
  </head>
  
<h1>New Room</h1>

<%= form_with scope: :room, url: rooms_path, local: true do |form| %>

<% if @room.errors.any? %>
<div id="error_explanation">
	<h2>
		<%= pluralize(@room.errors.count, "error") %>
		prevented you from making this room:
	</h2>
	<ul>
	<% @room.errors.full_messages.each do |msg| %>
		<li><%= msg %></li>
	<% end %>
	</ul>
</div>
<% end %>

<p>
	<%= form.label "name" %><br>
	<%= form.text_field :name, placeholder: "Put your room name here" %>
</p>

<p>
	<%= form.label 'Description' %><br>
	<%= form.text_field :description, placeholder: "What is your room for?" %>
</p>


<p>
	<%= form.submit "Create Room", :class => "button"%>
</p>

<% end %>
 </body>
</html>

app/views/rooms/present.html.erb
<h1>Presentation View</h1>

<script>
  var presenting = true;
</script>

<%= render "rooms/quizjs.html.erb" %>

<h1><%= @room.name %></h1>
Your name is <span><%= @username %></span>

<% if @room.state.nil? %>
    <h2 id="not_started">Quiz not yet started.</h2>
<% elsif @room.state == "active" %>
    <h2 id="started">Awaiting next question.</h2>
<% elsif @room.state == "finished" %>
    <h2 id="finished">The quiz is over.</h2>
<% end %>

<% if @finished and @room.state == "active" %>
    <h2 id="finished">You have reached the last question.</h2>
<% end %>

<% if @room.active_question.present? %>
<h2><span id="question_id">Question #<%= @question_idx %></span>: <%= @question.body %></h2>
<% alpha = "ABCDEFGHIJKLMNOPQRSTUVWXYZ".split("") %>
  <% @question.answers.each.with_index do |answer, idx| %>
      <%= alpha[idx] %>.) <%= answer.text %> <br>
  <% end %>



<script>
    var question_id = <%= @question.id %>;
    var responses =  <%== Response.where(question_id: @question.id).to_json %>;
</script>

<div id="responses" style="width: 100%; height: 800px;"></div>
<%= render "rooms/responses.html.erb" %>
<% end %>


<h2>Users in the room:</h2>

<style>
  .users {
    list-style-type: none;
  }
  .li_user {
    float: left;
    display: inline;
    margin: 10px;
  }
</style>

<ul class="users" style="background: rgba(0, 0, 0, 0);">
  <% @room.student_infos.each do |info| %>
    <li class="li_user">
      <%= info.name %>
    </li>
  <% end %>
</ul>

app/views/rooms/present2.html.erb
<!doctype html>
<html lang="en">
<head>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script>
      var presenting = true;
  </script>
  <%= render "rooms/quizjs.html.erb" %>

  <style>
    html, body {
      height: 100%;
      margin: 0;
    }
    .content {
      min-height: 100%;
      width: 1000px;
      margin: 0 auto;
      box-shadow: 12px 0 15px -4px rgba(0, 0, 0, 0.3), -12px 0 8px -4px rgba(0, 0, 0, 0.3);
    }
    .info {
      min-height: 100%;
      width: 33.33%;
      float: left;
      padding: 5px;
      box-sizing: border-box;
    }
    .question {
      width: 66.66%;
      float: right;
      padding: 20px;
      box-sizing: border-box;
      padding-left: 50px;
    }
    .header {
      height: 25px;
      line-height: 25px;
      background: #356C82;
      font-weight: bold;
      color: white;
      text-shadow: 0px 1px 0px rgba(0, 0, 0, 0.25);
      padding: 3px;
      box-sizing: border-box;
    }
    .footer {
      height: 50px;
      margin-top: -50px;
    }
    body {
      font: 16px Sans-Serif;
    }
    h1 {
      margin: 0 0 20px 0;
    }
    p {
      margin: 20px 0 0 0;
    }
    footer {
      background: #3290B5;
      color: white;
      line-height: 50px;
      padding: 0 20px;
    }
    .box {
      margin-bottom: 20px;
      box-shadow: 2px 2px 5px 0px rgba(0, 0, 0, 0.3);
      padding: 5px;
      box-sizing: border-box;
    }
  </style>
  <title>QuizClicker</title>
</head>

<body>
<div class="content">
  <div class="info">
    <div>
      <h2><%= @room.name %></h2>
    </div>
    <div class="box" style="height: 75px; line-height: 50px;">
      <div class="header">
        Status
      </div>
      <% if @room.state.nil? %>
          <span id="not_started">Quiz not yet started.</span>
      <% elsif @room.state == "active" %>
          <span id="started">Awaiting next question.</span>
      <% elsif @room.state == "finished" %>
          <span id="finished">The quiz is over.</span>
      <% end %>
    </div>
    <div class="box" style="height: 100px; overflow-y: scroll;">
      <div class="header">
        Events
      </div>
      <ul id="events">

      </ul>
    </div>
    <div class="box" style="min-height: 100px;">
      <div class="header" style="margin-bottom: 10px;">
        Online users
      </div>
      <div id="theusers">
        <% @room.student_infos.each do |info| %>
              <%= info.name %>,
        <% end %>
      </div>
    </div>
    <div class="box" style="min-height: 100px;">
      <div class="header" style="margin-bottom: 10px;">
        Responses
      </div>
      <div id="responses">

      </div>
    </div>
  </div>

  <div class="question">
    <div class="header" style="text-align: right;">
      Question <b><%= @room.active_question %> of <%= @room.questions.length %></b>
    </div>
    <div class="question_body" style="margin-top: 40px;">
      <% if @room.active_question.present? and @room.state == "active" %>
        <h1><%= @question.body %></h1>
        <ul style="font-size: 32px; list-style-type: none;">
              <% alpha = "ABCDEFGHIJKLMNOPQRSTUVWXYZ".split("") %>
              <% @question.answers.each.with_index do |answer, idx| %>
              <li><b><%= alpha[idx] %></b>&nbsp;&nbsp;&nbsp; <%= answer.text %></li>
              <% end %>
        </ul>
      <% else %>
        <h1>No question active yet.</h1>
      <% end %>
    </div>
  </div>
</div>

<footer class="footer">
  <div class="join" style="float: left; font-weight: bold;">
    Join this room: quizclicker.net/<%= @room.roomcode %>
  </div>
  <img src="/quizlogo.png" style="float: right; height: 40px; padding-top: 5px;" />
</footer>
</body>

<% if @room.active_question.present? %>

    <% if @room.active_question.present? and @room.state == "active" %>

<script>
    function event(msg) {
        $("#events").prepend("<li>" + msg + "</li>");
    }

    var question_id = <%= @question.id %>;
    var responses =  <%== Response.where(question_id: @question.id).to_json %>;
</script>

    <%= render "rooms/responses.html.erb" %>

<script>


</script>

<% end %>

<script>
  var room_id = "<%= @room.id %>";
  var curnames = <%== @room.student_infos.map{ |s| s.name}.to_json %>;

  setInterval(function() {
    $.get('/api/student_info/' + room_id, function(data) {
        var names = data.map(function (x) {
            return x.name;
        });

        for(var old of curnames) {
          if(names.indexOf(old) < 0)
              event(old + " was kicked!");
        }

        for(var newn of names) {
            if(curnames.indexOf(newn) < 0) {
                event(newn + " has joined!")
            }
        }

        document.getElementById("theusers").innerHTML = names.join(", ");
        curnames = names;
    });
  }, 400);
</script>

    <%end%>

</html>

app/views/rooms/quiz.html.erb
<%= render "rooms/quizjs.html.erb" %>
<%= render "rooms/kick.html.erb" %>


<script>
    var presenting = false;
</script>

<h1><%= @room.name %></h1>
Your name is <span><%= @username %></span>

<% if @room.state.nil? %>
    <h2 id="not_started">Quiz not yet started.</h2>
<% elsif @room.state == "active" %>
    <h2 id="started">Awaiting next question.</h2>
<% elsif @room.state == "finished" %>
    <h2 id="finished">The quiz is over.</h2>
<% end %>

<% if @finished and @room.state == "active" %>
  <h2 id="finished">You have reached the last question.</h2>
<% end %>

<% if @has_res %>
    Your last response was: <i><%= @last_res_text %></i><br>
    <br>

<% else %>
    You haven't answered any questions yet.
<% end %>

app/views/rooms/quiz_question.html.erb
<%= render "rooms/quizjs.html.erb" %>
<%= render "rooms/kick.html.erb" %>

<h2><span id="seconds">60 </span> seconds left</h2>

<h2><span id="question_id">Question #<%= @question_idx %></span>: <%= @question.body %></h2>
<% alpha = "ABCDEFGHIJKLMNOPQRSTUVWXYZ".split("") %>
<form method="post" style="margin: 50px;">
  <% @question.answers.each.with_index do |answer, idx| %>
      <input type="radio" name="response" value="<%= idx %>" id="option<%= idx %>"/> <%= alpha[idx] %>.) <%= answer.text %> <br>
  <% end %>
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>"/>
  <button>Submit Answer</button>
</form>

<script>
  var time = 60;
  var secs = document.getElementById("seconds");

  setInterval(function() {
    time--;
    if(time == 0)
        window.location.href = "/rooms/quiz/"  + <%= @room.id.to_s %>;
    secs.innerHTML = time;

  }, 1000)
</script>

app/views/rooms/remote.erb
<% if @room.state == 'active' %>
<div id="quiz_active">now active</div>
<% end %>

<% if @room.state == 'active' and @room.active_question.present? %>
    <div id="quiz_showing_question">quiz on question <%= @room.active_question %></div>
<% end %>
<a id="next_question" class="button" href="/rooms/remote/<%= @room.id %>/next">Next Question</a>

<%= render "rooms/kickusers.html.erb" %>

app/views/rooms/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @room.name %>
  <strong>Password:</strong>
  <span id="password"><%= @room.password %></span>
  <strong>Roomcode:</strong>
  <span id="roomcode"><%= @room.roomcode %></span>
</p>

<a class="button" id="start_quiz" href="/rooms/remote/<%= @room.id.to_s %>">Start Quiz</a>

<%= link_to 'Delete Room', [@room],
            method: :delete, data: {confirm: 'Are you sure?'}, :class => "button delete_room" %>

<a class="button" id="reset_quiz" href="/rooms/reset/<%= @room.id.to_s %>">Reset Quiz</a>

<br><br><a class="button" id="present_quiz" href="/rooms/present/<%= @room.id.to_s %>">Present Quiz</a>
<h2>Questions</h2>
<% @room.questions.each do |question| %>

    <div id="nicebox">
      <p style="text-decoration:none">
        <%= question.body %>
        <%= link_to 'View', [question.room, question], :class => "button question" %>
      </p>

      <p>


      <p>
        <%= link_to 'Delete Question', [question.room, question],
                    method: :delete, data: {confirm: 'Are you sure?'}, :class => "button" %>
      </p>
    </div>
<% end %>

<h2>Add a question:</h2><br>
<%= form_with(model: [@room, @room.questions.build], local: true) do |form| %>
    <p>
      <%= form.label :question %>
      <r>
        <%= form.text_field :body %>
    </p>
    <p>
      <%= form.submit "Create Question", :class => "button" %>
    </p>
<% end %>

app/views/rooms/unauthed.html.erb
<strong>Needs Authentication</strong>
<% flash.each do |k, v| %>
	<p><%= v %></p>
<% end %>

<%= form_tag("/rooms/auth", method: "post") do %>
	<%= hidden_field_tag(:id, params[:id]) %>
	<%= password_field_tag(:password) %>
	<%= submit_tag("Authenticate") %>
<% end %>